import Link from "next/link";
import { requireContext } from "@/lib/auth";
import { getT } from "@/lib/i18n/server";
import { visibleNav } from "@/lib/nav";
import { permissionLabel } from "@/lib/workflows/labels";
import { Card } from "./ui";

export async function RoleAccessGuide() {
  const ctx = await requireContext();
  const { locale, t } = await getT();
  const L = (en: string, bn: string) => locale === "bn" ? bn : en;
  const tools = visibleNav(ctx.role, [...ctx.permissions]).filter(x => x.key !== "help");
  const roles = [
    [t.roles.super_admin, L("School owner: all school tools, staff invitations, role changes and individual permission controls. Can delete unused records and archive students/staff.", "স্কুলের মালিক: সব অপশন, কর্মীর আমন্ত্রণ, ভূমিকা ও ব্যক্তিগত অনুমতি নিয়ন্ত্রণ। অব্যবহৃত রেকর্ড মুছতে ও শিক্ষার্থী/কর্মী সংরক্ষণ করতে পারেন।")],
    [t.roles.admin, L("School administration: students, guardians, teachers, classes, attendance, homework, exams, notices and permitted finance tools. Can delete unused records and archive students/staff. Owner controls staff accounts and permission grants.", "স্কুল প্রশাসন: শিক্ষার্থী, অভিভাবক, শিক্ষক, শ্রেণি, হাজিরা, বাড়ির কাজ, পরীক্ষা, নোটিশ ও অনুমোদিত হিসাবের অপশন। অব্যবহৃত রেকর্ড মুছতে ও শিক্ষার্থী/কর্মী সংরক্ষণ করতে পারেন। মালিক কর্মীর অ্যাকাউন্ট ও অনুমতি নিয়ন্ত্রণ করেন।")],
    [t.roles.teacher, L("Assigned classes only: view pupils and guardian contacts, prepare guardian messages, take attendance, manage homework, enter permitted marks and publish class notices. No deletion, school-wide finance or account management by default. The owner must assign the teacher to sections first.", "নির্ধারিত শ্রেণি: শিক্ষার্থী ও অভিভাবকের যোগাযোগ দেখা, বার্তা তৈরি, হাজিরা, বাড়ির কাজ, অনুমোদিত নম্বর ও শ্রেণির নোটিশ। সাধারণত রেকর্ড মুছতে, স্কুলের হিসাব বা অ্যাকাউন্ট পরিচালনা করতে পারবেন না। আগে মালিক শিক্ষককে শাখায় দায়িত্ব দেবেন।")],
    [t.roles.accountant, L("Accounts: permitted fees, receipts, expenses and reports, with student lookup. Cannot delete records or manage staff roles.", "হিসাব: অনুমোদিত বেতন, রসিদ, খরচ, প্রতিবেদন ও শিক্ষার্থী খোঁজা। রেকর্ড মুছতে বা কর্মীর ভূমিকা পরিচালনা করতে পারবেন না।")],
    [t.roles.guardian, L("Parent portal: linked children only, their attendance, published homework/results and fees. Can update their own contact details. Cannot edit school records or delete data.", "অভিভাবক পোর্টাল: শুধু যুক্ত সন্তানের হাজিরা, প্রকাশিত বাড়ির কাজ/ফলাফল ও বেতন। নিজের যোগাযোগের তথ্য সম্পাদনা করতে পারেন। স্কুলের রেকর্ড সম্পাদনা বা মুছতে পারবেন না।")],
  ];
  return <div className="mb-4 space-y-4">
    <Card className="space-y-3 p-4">
      <h2 className="text-lg font-bold">{L("Your access", "আপনার অনুমতি")}: {t.roles[ctx.role]}</h2>
      <p className="text-sm text-ink-2">{L("These are the tools available to your current signed-in account. Each person signs in with their own invited account; changing language does not change their role.", "বর্তমান সাইন ইন অ্যাকাউন্টের অপশন নিচে দেওয়া হলো। প্রত্যেকে নিজের আমন্ত্রিত অ্যাকাউন্টে সাইন ইন করবেন; ভাষা পরিবর্তন করলে ভূমিকা পরিবর্তন হয় না।")}</p>
      <div className="flex flex-wrap gap-2">{tools.map(x => <Link key={x.href} href={x.href} className="inline-flex min-h-11 items-center rounded-xl bg-surface-2 px-3 font-semibold text-brand">{t.nav[x.key]}</Link>)}</div>
      {ctx.role === "teacher" && <p>{L(`Assigned sections: ${ctx.teachesSections.length}. If zero, ask the owner to open Teachers → Assign class/subject and link your staff invitation.`, `নির্ধারিত শাখা: ${ctx.teachesSections.length}। শূন্য হলে মালিককে শিক্ষক → শ্রেণি/বিষয়ের দায়িত্ব দিতে এবং কর্মীর আমন্ত্রণ যুক্ত করতে বলুন।`)}</p>}
      {ctx.role !== "guardian" && <details><summary className="cursor-pointer min-h-11 py-2 font-semibold">{L("Your effective permissions", "আপনার কার্যকর অনুমতি")}</summary>{ctx.role === "super_admin" ? <p>{L("All school permissions", "স্কুলের সব অনুমতি")}</p> : <ul className="list-disc space-y-1 pl-5">{[...ctx.permissions].sort().map(p => <li key={p}>{permissionLabel(p,p.replace(/[._]/g," "),locale)}</li>)}</ul>}</details>}
    </Card>
    <Card className="space-y-3 p-4"><h2 className="text-lg font-bold">{L("How each role sees the app", "প্রতিটি ভূমিকা অ্যাপ কীভাবে দেখে")}</h2><p className="text-sm text-ink-2">{L("Menus and bottom tabs change with the role. The owner may grant or deny extra permissions; your current tools above are authoritative. Deletion remains admin-only even when a teacher has extra edit permissions.", "ভূমিকা অনুযায়ী মেনু ও নিচের অপশন পরিবর্তন হয়। মালিক অতিরিক্ত অনুমতি দিতে বা বন্ধ করতে পারেন; উপরের বর্তমান অপশনই আপনার প্রকৃত অনুমতি। শিক্ষককে অতিরিক্ত সম্পাদনার অনুমতি দিলেও রেকর্ড মুছতে পারবেন না।")}</p>{roles.map(([name, text]) => <div key={name} className="border-t border-line pt-3"><h3 className="font-bold">{name}</h3><p className="mt-1 text-sm">{text}</p></div>)}</Card>
    {ctx.role !== "guardian" && <Card className="space-y-3 p-4"><h2 className="text-lg font-bold">{L("Send a guardian message", "অভিভাবককে বার্তা পাঠান")}</h2><ol className="list-decimal space-y-2 pl-5"><li>{L("Students → select a student → Edit → Guardian. Save their name, relationship and mobile number.", "শিক্ষার্থী → শিক্ষার্থী নির্বাচন → সম্পাদনা → অভিভাবক। নাম, সম্পর্ক ও মোবাইল নম্বর সংরক্ষণ করুন।")}</li><li>{L("Admins: More → Guardians → Message guardian. Teachers: Students → assigned student → Guardian → Message guardian. Choose a template or write your own message.", "অ্যাডমিন: আরও → অভিভাবক → অভিভাবককে বার্তা। শিক্ষক: শিক্ষার্থী → নির্ধারিত শিক্ষার্থী → অভিভাবক → অভিভাবককে বার্তা। নমুনা বাছুন অথবা নিজের বার্তা লিখুন।")}</li><li>{L("Replace every [placeholder] with the correct details. WhatsApp and SMS buttons then appear.", "[বন্ধনীর] সব তথ্য সঠিকভাবে পূরণ করুন। এরপর WhatsApp ও SMS অপশন আসবে।")}</li><li>{L("Choose WhatsApp or SMS, review the prepared message in that app and press Send there.", "WhatsApp অথবা SMS বাছুন, সেই অ্যাপে বার্তা যাচাই করে Send চাপুন।")}</li></ol><p className="text-sm text-ink-2">{L("This opens your messaging app; the school app does not send automatically or confirm delivery. Automatic event notifications require a connected provider. SMS availability depends on your device and mobile service.", "এটি আপনার বার্তার অ্যাপ খুলবে; স্কুল অ্যাপ স্বয়ংক্রিয়ভাবে পাঠায় না বা পৌঁছানো নিশ্চিত করে না। স্বয়ংক্রিয় বার্তার জন্য সেবা সংযুক্ত করতে হবে। SMS আপনার ডিভাইস ও মোবাইল সেবার ওপর নির্ভর করে।")}</p></Card>}
    <Card className="space-y-2 p-4"><h2 className="text-lg font-bold">{L("Delete and archive", "মুছুন ও সংরক্ষণ")}</h2><p>{L("Only Admin and Super Admin see removal controls. Open the control, enter a reason, tick confirmation and confirm. Students and staff are archived to preserve history. Unused records can be permanently deleted; linked records, published results and approved expenses are protected. Payment and fee mistakes use reversal or cancellation, and attendance uses correction.", "শুধু অ্যাডমিন ও সুপার অ্যাডমিন রেকর্ড সরানোর অপশন দেখবেন। অপশন খুলে কারণ দিন, নিশ্চিত করার ঘর টিক দিয়ে নিশ্চিত করুন। শিক্ষার্থী ও কর্মীর ইতিহাস সংরক্ষিত থাকবে। অব্যবহৃত রেকর্ড স্থায়ীভাবে মুছতে পারেন; যুক্ত রেকর্ড, প্রকাশিত ফলাফল ও অনুমোদিত খরচ সুরক্ষিত। পেমেন্ট ও বেতনের ভুল রিভার্স বা বাতিল করুন; হাজিরা সংশোধন করুন।")}</p><p className="text-sm text-ink-2">{L("To stop an account signing in, the school owner uses Staff → Suspend. Archiving a teacher record does not suspend their account.", "সাইন ইন বন্ধ করতে মালিক কর্মী ব্যবস্থাপনা → স্থগিত ব্যবহার করবেন। শিক্ষকের রেকর্ড সংরক্ষণ করলে অ্যাকাউন্ট বন্ধ হয় না।")}</p></Card>
  </div>;
}
