const BN: Record<string, string> = {
  "students.view": "শিক্ষার্থীর তথ্য দেখুন",
  "students.create": "শিক্ষার্থী ভর্তি করুন",
  "students.edit": "শিক্ষার্থীর তথ্য সম্পাদনা",
  "students.archive": "শিক্ষার্থীকে নিষ্ক্রিয় করুন",
  "guardians.manage": "অভিভাবক ও আমন্ত্রণ পরিচালনা",
  "teachers.manage": "শিক্ষক ও দায়িত্ব পরিচালনা",
  "academics.manage": "শ্রেণি, বিষয় ও রুটিন পরিচালনা",
  "attendance.view": "হাজিরা দেখুন",
  "attendance.create": "হাজিরা নিন",
  "attendance.correct": "পুরোনো হাজিরা সংশোধন",
  "homework.manage": "বাড়ির কাজ পরিচালনা",
  "exams.manage": "পরীক্ষা ও গ্রেড পরিচালনা",
  "marks.enter": "নম্বর প্রদান",
  "results.publish": "ফলাফল প্রকাশ",
  "fees.view": "ফি ও পরিশোধ দেখুন",
  "fees.configure": "ফি নির্ধারণ",
  "fees.invoice": "ফি ধার্য করুন",
  "fees.collect": "ফি আদায়",
  "fees.adjust": "ছাড় ও মওকুফ",
  "fees.reverse": "ভুল পরিশোধ বাতিল",
  "fees.refund": "অর্থ ফেরত",
  "expenses.view": "ব্যয় দেখুন",
  "expenses.create": "ব্যয় লিখুন",
  "expenses.approve": "ব্যয় অনুমোদন বা প্রত্যাখ্যান",
  "reports.view": "প্রতিবেদন দেখুন",
  "reports.export": "প্রতিবেদন ডাউনলোড",
  "notices.manage": "স্কুলের নোটিশ প্রকাশ",
  "staff.manage": "কর্মী ও অনুমতি পরিচালনা",
  "settings.manage": "স্কুলের সেটিংস পরিবর্তন",
  "audit.view": "পরিবর্তনের লগ দেখুন",
};
export function permissionLabel(
  key: string,
  description: string,
  locale: "bn" | "en",
) {
  return locale === "bn" ? (BN[key] ?? description) : description;
}
